spring:
  application:
    name: eboutique
  datasource:
    username: root
    password:  # VÃ©rifiez que c'est le bon mot de passe
    url: jdbc:mysql://localhost:3306/e_boutique
  jpa:
    hibernate:
      ddl-auto: create